### ISSUE TITLE
resource mongodbatlas_project_invitation is created during each terrafrom apply

### ISSUE THREAD

**Issue by aston-r** [mongodb/terraform-provider-mongodbatlas#652]
Hi,

terraform: v1.1.3
mongodb/mongodbatlas: v1.1.1

I want to create the project and want to add users to the project.
```
resource "mongodbatlas_project" "this" {
  count  = var.create ? 1 : 0
  name   = var.project_name
  org_id = var.org_id
}

resource "mongodbatlas_project_invitation" "this" {
  for_each    = var.create ? var.project_users : {}
  username    = each.value.email
  project_id  = mongodbatlas_project.this[0].id
  roles       = each.value.roles
}
```

STR:
- terraform apply ( terraform show that it will create mongodbatlas_project_invitation.this resource )
- terraform apply ( terraform show against that it will create mongodbatlas_project_invitation.this resource)

Actual Result:
- After each terraform apply, all users receive a notification...

**Comment by yevhen-lodovyi** [comment]
this issue is fixed in 1.2.0 version

**Comment by yevhen-lodovyi** [comment]
I thought that the issue was fixed in 1.2.0 version, but it is not. Previously the resource was recreated during each apply. Now approximately after 48 hours, terraform reports that it is going to recreate the resource again....


````
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":


  # mongodbatlas_project_invitation.this["yevhen"] has been deleted
  - resource "mongodbatlas_project_invitation" "this" {
      - created_at       = "2022-01-15T11:15:11Z" -> null
      - expires_at       = "2022-02-14T11:15:11Z" -> null
      - id               = "XXX" -> null
      - invitation_id    = "XXX" -> null
      - inviter_username = "XXX" -> null
      - project_id       = "XXX" -> null
      - roles            = [
          - "GROUP_OWNER",
        ] -> null
      - username         = "XXX" -> null
    }

````

**Comment by aston-r** [comment]
Hi,

Retested on 1.2.0 version. The issue is still present:
````
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":


  # mongodbatlas_project_invitation.this["yevhen"] has been deleted
  - resource "mongodbatlas_project_invitation" "this" {
      - created_at       = "2022-01-15T11:15:11Z" -> null
      - expires_at       = "2022-02-14T11:15:11Z" -> null
      - id               = "XXX" -> null
      - invitation_id    = "XXX" -> null
      - inviter_username = "XXX" -> null
      - project_id       = "XXX" -> null
      - roles            = [
          - "GROUP_OWNER",
        ] -> null
      - username         = "XXX" -> null
    }

````

**Comment by themantissa** [comment]
@aston-r note that inviting the user to an org/project simply a step in the process.  Once the user has accepted the invitation it is deleted in the system.   Hence you have to then delete it within your Terraform configuration.  As noted in the documentation for org invitations (will add to project):

    NOTE: Possible provider behavior depending on the invitee's action:

-         If the user has not yet accepted the invitation, the provider leaves the invitation as is.
- If the user has accepted the invitation and is now an organization member, the provider will remove the invitation from the Terraform state. The invitation must then be removed from the Terraform resource configuration.
- If the user accepts the invitation and then leaves the organization, the provider will re-add the invitation if the resource definition is not removed from the Terraform configuration.

**Comment by aston-r** [comment]
@themantissa 

> Once the user has accepted the invitation it is deleted in the system. Hence you have to then delete it within your Terraform configuration

Thank you for the explanation, but terraform is the tool to manage the infrastructure as a code and this is not possible with this resource.  The main point with terraform is that you apply the stack multiple times and you do not have any changes. In your case, we have the resource(mongodbatlas_project_invitation) that act as the script, but not how the terraform code suppose to work.  

I have a simple use-case: I want to specify the list of users that should have access to the project and commit these changes to the repository. At any time, I can add/remove the new users and terraform should add/remove them, as it works with mongodbatlas_database_user


To make this resource usable it would be nice to have the following:
* if there is user in the project then keep the invitation in the tfstate and do not send the invitation.
* If there is no user in the project, send the invitation once again

**Comment by themantissa** [comment]
@aston-r I'm very much aware of how Terraform should ideally work and I hear you. What it sounds like you want is simply a better way to mange Atlas Users with Terraform.  The invitation is simply a part of that overall user management process.  Invitations has been added to the provider but, due to the way the underlying system works, we have not been able to add full Atlas User management without it being as problematic as invitations is (for a different reason but if we added it as is, you would see similar challenges).   I'll continue to work with our internal teams to improve the way the system works so we can better expose it via Terraform, in a way that adheres to general I@C principles, as well as with our Terraform developers to find a way to make what we do have better.    Furthermore, Invitations was a community submission, which we very much appreciate, and hopefully in the near term we'll be able to look for opportunities to improve the experience with it.

**Comment by jfeddern** [comment]
Hi there,
maybe one idea how this could be solved, as I just hit the same issue within our setup with this terraform resource.

Could we maybe check the status of the user in advance and based on the status the invitation will be send or not?
e.g.
When no user can be retrieved from the atlas project, than an invitation should be send.
If user has status pending in the project, no invitation will be send.
If user is assigned to project and status is (something which means that the user accepted the invitation), no invitation will be send.

**Comment by dgteixeira** [comment]
Hello all, any updates on this? :)

What I will attempt to do, to counter this is:
 1 -  Since we use IdP to federate the user base, make sure the user logs in before getting a project.
 2 -  Create a team with that user;
 3 - Create the project and assign the previous team to that user.

It is not ideal, but it might work.

**Comment by leo-ferlin-sutton** [comment]
How would the maintainers feel about this idea to fix the invitation ressource:

Instead of deleting the ressource from the state when the invitation is accepted, add a computed `Attributes` called `invitation_status` that could store the status of the invitation (`ongoing`,`expired`,`accepted`). 

The mechanism that removes the invitation from the state could instead change the status of this attribute and avoid the terraform anti-pattern it's currently doing.


I understand this would only solve the `Terraform tries to create the invitation each time` and not the rest of @aston-r's concerns (no real user management, not way to revoke user access from terraform).

**Comment by themantissa** [comment]
Hi all - wanted to provide a quick update here (btw I'm the Product Manager at MDB for Terraform 👋 )   First we just released 1.4.2 which support federation management.  This may help some who have posted who are watching here.  Two, it's on our roadmap to improve invitations/user management.   Adding invitations, while not ideal for all, did help some customers quite a bit.  But we hear you that it's not ideal across the board.   When I have more information/ETA it will be shared.  In the meantime please keep the ideas coming (@leo-ferlin-sutton) and we'll keep working at knocking out the functionality you need.  cc @ZuhairAhmed

**Comment by themantissa** [comment]
Close this out but again, invitations/users/etc is in the backlog and we'll update via feedback.mongodb.com.

**Comment by Alexlofern** [comment]
Hello @themantissa,

I have the same problem, what is the solution to this issue? You can't close it and ignore it as if there wasn't a problem.

Regards
