### ISSUE TITLE
mongodbatlas_alert_configuration - api_token keeps wanting to change

### ISSUE THREAD

**Issue by bluemalkin** [mongodb/terraform-provider-mongodbatlas#863]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
Terraform: v1.2.1
Provider: 1.4.6
```

### Terraform Configuration File 
```hcl
resource "mongodbatlas_alert_configuration" "no-primary" {
  project_id = mongodbatlas_project.project.id
  event_type = "NO_PRIMARY"
  enabled    = true

  notification {
    delay_min     = 0
    interval_min  = 5
    email_enabled = true
    sms_enabled   = false
    roles         = ["GROUP_OWNER"]
    type_name     = "GROUP"
  }

  notification {
    channel_name  = "#monitoring-prd"
    api_token     = data.google_secret_manager_secret_version.slack-token.secret_data
    delay_min     = 0
    interval_min  = 5
    email_enabled = false
    sms_enabled   = false
    roles         = []
    type_name     = "SLACK"
  }
}
```

### Expected Behavior
No change

### Actual Behavior
Terraform keeps wanting to update the `api_token` despite no change and I keep applying:
```hcl
  # mongodbatlas_alert_configuration.no-primary will be updated in-place
  ~ resource "mongodbatlas_alert_configuration" "no-primary" {
        id                     = "REDACTED"
        # (6 unchanged attributes hidden)



      ~ notification {
          ~ api_token              = (sensitive value)
            # (22 unchanged attributes hidden)
        }
        # (2 unchanged blocks hidden)
    }
```

**Comment by nicolasvan** [comment]
We're seeing the same behaviour which started a few hours ago. Wild guess would be some Atlas API change that maybe doesn't return secrets anymore?

We're working around it by adding this block to `mongodbatlas_alert_configuration`:
```terraform
lifecycle {
  ignore_changes = [
    notification[0].api_token
  ]
}
```

**Comment by bluemalkin** [comment]
> We're seeing the same behaviour which started a few hours ago. Wild guess would be some Atlas API change that maybe doesn't return secrets anymore?
> 
> We're working around it by adding this block to `mongodbatlas_alert_configuration`:
> 
> ```terraform
> lifecycle {
>   ignore_changes = [
>     notification[0].api_token
>   ]
> }
> ```

Yep I had to do the same.

**Comment by evertsd** [comment]
Thanks for the feedback.

We've replicated the issue and are working on a solution

**Comment by intelliping** [comment]
any update for the issue?

**Comment by Zuhairahmed** [comment]
Hi @LipingSun, we are working on a solution and internal ticket is [INTMDB-426](https://jira.mongodb.org/browse/INTMDB-426). You can expect this to be included as part a near term release and will alert this thread when fix is out.

**Comment by bennyrw** [comment]
With the same provider version I've noticed the same issue but on the `service_key` argument used to send the alert to PagerDuty.

Maybe it's the same underlying cause, but in my case the value stored in the terraform state file is redacted so terraform always wants to always reapply the change.

Please can you include the `service_key` argument in the fix you are working on? 🙏  Thanks

**Comment by neelrr1** [comment]
Hopefully they fix the underlying issue that will solve it for both fields, but yes can confirm that this is affecting PagerDuty `service_key` as well.

**Comment by martinstibbe** [comment]
@bluemalkin @neelrr1 v1.6.1 release will contain this fix

**Comment by Zuhairahmed** [comment]
@bluemalkin @LipingSun @bennyrw @neelrr1 we released v1.6.1 today which includes this fix. Feel free to upgrade Terraform Provider versions and let us know if this resolves the issue.

**Comment by neelrr1** [comment]
As far as I can tell, this has not resolved the issue. I still see extra "changes" to `mongodbatlas_alert_configuration` like:
```
~ notification {
          ~ api_token     = (sensitive value)
```

I'm on TF 0.13.7 with version 1.6.1 of the Atlas provider.

**Comment by martinstibbe** [comment]
@neelrr1 Could you verify if what is stored in state file for api_token = value in your TF file ?
As a terraform apply should set that value to match value in terraform and ignore value coming back from API as it is masked

i.e. TF = ABCDEFGH1234  statefile = ABCDEFGH1234 vs TF = ABCDEFGH1234  statefile = ********1234

**Comment by neelrr1** [comment]
> @neelrr1 Could you verify if what is stored in state file for api_token = value in your TF file ? As a terraform apply should set that value to match value in terraform and ignore value coming back from API as it is masked
> 
> i.e. TF = ABCDEFGH1234 statefile = ABCDEFGH1234 vs TF = ABCDEFGH1234 statefile = ********1234

Ah nevermind, I hadn't done a `terraform apply` yet. This fix is awesome!

**Comment by legal90** [comment]
@martinstibbe This issue still exists in another resource - `mongodbatlas_third_party_integration`
It always wants to update the `api_key`, while the actual value remains the same:

```
  # mongodbatlas_third_party_integration.atlas_datadog[0] will be updated in-place
  ~ resource "mongodbatlas_third_party_integration" "atlas_datadog" {
      ~ api_key                     = (sensitive value)
        id                          = "cHJvamVjdF9pZA==:NWY1OGFhMjczYzE1YzQ2NGNkNTdmYWVm-dHlwZQ==:REFUQURPRw=="
        # (9 unchanged attributes hidden)
    }

```

The symptoms are exactly the same as you described above:  in the terraform state dumped by `terraform state pull` the value of `api_key` is masked and looks like `****************************a1b2c3`.  And `terraform apply` doesn't fix it.

Reproduced with mongodbatlas provider `1.6.1` and terraform `1.3.6`

Should I create a new issue about that?

**Comment by martinstibbe** [comment]
@legal90 Yes a new issue would work fine to track will get this into another release to get those API keys stable Thanks

**Comment by legal90** [comment]
@martinstibbe I created a new issue: https://github.com/mongodb/terraform-provider-mongodbatlas/issues/963
